import { Product } from './supabase'

// Database completo di prodotti Fortinet per il mercato italiano
export const productsData: Product[] = [
  // FortiGate Series
  {
    id: '1',
    name: 'FortiGate 40F',
    model: 'FG-40F',
    category: 'FortiGate',
    subcategory: 'Entry Level',
    description: 'Firewall di nuova generazione compatto per piccole imprese e filiali. Offre protezione completa con throughput fino a 5 Gbps, VPN SSL/IPsec, protezione dalle minacce e controllo delle applicazioni.',
    short_description: 'Firewall NGFWcompatto ideale per piccole imprese con prestazioni fino a 5 Gbps',
    price: 649,
    discount_price: 599,
    features: [
      'Throughput firewall fino a 5 Gbps',
      'Protezione dalle minacce integrata',
      'VPN SSL e IPsec',
      'Controllo applicazioni',
      'Web filtering',
      '12 porte GE RJ45',
      '2 porte GE RJ45 WAN',
      'Interfaccia WiFi integrata opzionale',
    ],
    specifications: {
      'Throughput Firewall': '5 Gbps',
      'Throughput IPS': '600 Mbps',
      'Throughput NGFW': '250 Mbps',
      'Throughput VPN IPsec': '1.8 Gbps',
      'Tunnel VPN SSL': '200',
      'Tunnel VPN IPsec': '400',
      'Porte': '12x GE RJ45 + 2x GE RJ45 WAN',
      'Storage': '480 GB',
    },
    image_url: '/images/products/fortigate-40f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiGate 40F - Firewall NGFW per Piccole Imprese | FortiStore Italia',
    meta_description: 'Acquista FortiGate 40F, firewall di nuova generazione per piccole imprese. Throughput 5 Gbps, VPN, protezione minacce. Rivenditore ufficiale Fortinet in Italia.',
    meta_keywords: ['fortigate 40f', 'firewall piccole imprese', 'ngfw fortinet', 'fortigate prezzo', 'firewall italia'],
    slug: 'fortigate-40f',
  },
  {
    id: '2',
    name: 'FortiGate 60F',
    model: 'FG-60F',
    category: 'FortiGate',
    subcategory: 'Entry Level',
    description: 'Firewall NGFW ad alte prestazioni per piccole e medie imprese. Protezione completa con throughput fino a 10 Gbps, ideale per uffici distribuiti e sedi remote.',
    short_description: 'Firewall NGFW per PMI con throughput fino a 10 Gbps e protezione avanzata',
    price: 899,
    discount_price: 849,
    features: [
      'Throughput firewall fino a 10 Gbps',
      'Security Fabric integrato',
      'AI-powered threat protection',
      'SD-WAN avanzato',
      'Controllo applicazioni cloud',
      '16 porte GE RJ45',
      '2 porte GE RJ45 WAN dedicata',
      'Console port',
    ],
    specifications: {
      'Throughput Firewall': '10 Gbps',
      'Throughput IPS': '1.2 Gbps',
      'Throughput NGFW': '500 Mbps',
      'Throughput VPN IPsec': '3.5 Gbps',
      'Tunnel VPN SSL': '400',
      'Tunnel VPN IPsec': '800',
      'Porte': '16x GE RJ45 + 2x GE RJ45 WAN',
      'Storage': '480 GB SSD',
    },
    image_url: '/images/products/fortigate-60f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiGate 60F - Firewall NGFW per PMI | Acquista Online | FortiStore Italia',
    meta_description: 'FortiGate 60F firewall di nuova generazione per PMI. 10 Gbps throughput, SD-WAN, protezione AI. Prezzi competitivi. Rivenditore Fortinet Italia.',
    meta_keywords: ['fortigate 60f', 'firewall pmi', 'fortinet italia', 'ngfw 10gbps', 'sd-wan fortinet'],
    slug: 'fortigate-60f',
  },
  {
    id: '3',
    name: 'FortiGate 80F',
    model: 'FG-80F',
    category: 'FortiGate',
    subcategory: 'Mid-Range',
    description: 'Firewall di livello enterprise per medie imprese. Prestazioni eccezionali con throughput fino a 15 Gbps e funzionalità SD-WAN avanzate per ottimizzare la connettività multi-sede.',
    short_description: 'Firewall enterprise per medie imprese con 15 Gbps e SD-WAN avanzato',
    price: 1499,
    discount_price: 1399,
    features: [
      'Throughput firewall fino a 15 Gbps',
      'SD-WAN orchestrato',
      'FortiGuard AI-Powered Security',
      'Segmentazione avanzata',
      'Protezione zero-day',
      '16 porte GE RJ45 interne',
      '2 porte SFP',
      'Ridondanza hardware',
    ],
    specifications: {
      'Throughput Firewall': '15 Gbps',
      'Throughput IPS': '2 Gbps',
      'Throughput NGFW': '900 Mbps',
      'Throughput VPN IPsec': '5 Gbps',
      'Tunnel VPN SSL': '600',
      'Tunnel VPN IPsec': '2000',
      'Porte': '16x GE RJ45 + 2x SFP',
      'Storage': '960 GB SSD',
    },
    image_url: '/images/products/fortigate-80f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiGate 80F - Firewall Enterprise per Medie Imprese | FortiStore Italia',
    meta_description: 'FortiGate 80F firewall enterprise con 15 Gbps, SD-WAN orchestrato, protezione AI. Ideale per medie imprese italiane. Acquista ora.',
    meta_keywords: ['fortigate 80f', 'firewall enterprise', 'fortinet milano', 'sd-wan italia', 'firewall medie imprese'],
    slug: 'fortigate-80f',
  },
  {
    id: '4',
    name: 'FortiGate 100F',
    model: 'FG-100F',
    category: 'FortiGate',
    subcategory: 'Mid-Range',
    description: 'Soluzione firewall ad alte prestazioni per aziende in crescita. Throughput fino a 24 Gbps con protezione completa e capacità di gestire reti complesse multi-sede.',
    short_description: 'Firewall ad alte prestazioni con 24 Gbps per aziende in crescita',
    price: 2299,
    discount_price: 2149,
    features: [
      'Throughput firewall fino a 24 Gbps',
      'Protezione avanzata dalle minacce',
      'Security Fabric completo',
      'ZTNA (Zero Trust Network Access)',
      'Cloud security integration',
      '20 porte GE RJ45',
      '4 porte SFP',
      'Cluster HA supportato',
    ],
    specifications: {
      'Throughput Firewall': '24 Gbps',
      'Throughput IPS': '3.5 Gbps',
      'Throughput NGFW': '1.5 Gbps',
      'Throughput VPN IPsec': '9 Gbps',
      'Tunnel VPN SSL': '1000',
      'Tunnel VPN IPsec': '4000',
      'Porte': '20x GE RJ45 + 4x SFP',
      'Storage': '960 GB SSD',
    },
    image_url: '/images/products/fortigate-100f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiGate 100F - Firewall 24 Gbps per Aziende | Acquista | FortiStore Italia',
    meta_description: 'FortiGate 100F firewall 24 Gbps con Zero Trust e Security Fabric. Soluzione completa per aziende italiane. Rivenditore ufficiale Fortinet.',
    meta_keywords: ['fortigate 100f', 'firewall 24gbps', 'fortinet roma', 'zero trust firewall', 'security fabric'],
    slug: 'fortigate-100f',
  },
  {
    id: '5',
    name: 'FortiGate 200F',
    model: 'FG-200F',
    category: 'FortiGate',
    subcategory: 'High-End',
    description: 'Firewall enterprise di classe superiore per grandi organizzazioni. Prestazioni eccezionali con throughput fino a 52 Gbps e funzionalità di sicurezza avanzate per proteggere reti complesse.',
    short_description: 'Firewall enterprise 52 Gbps per grandi organizzazioni e data center',
    price: 4999,
    discount_price: 4699,
    features: [
      'Throughput firewall fino a 52 Gbps',
      'Protezione avanzata minacce APT',
      'Sandboxing inline',
      'Machine learning inspection',
      'Multi-VDOM support',
      '16 porte GE RJ45',
      '8 porte SFP+ 10GE',
      'Alimentazione ridondante',
    ],
    specifications: {
      'Throughput Firewall': '52 Gbps',
      'Throughput IPS': '8 Gbps',
      'Throughput NGFW': '3.5 Gbps',
      'Throughput VPN IPsec': '20 Gbps',
      'Tunnel VPN SSL': '4000',
      'Tunnel VPN IPsec': '10000',
      'Porte': '16x GE RJ45 + 8x SFP+ 10GE',
      'Storage': '1.92 TB SSD',
    },
    image_url: '/images/products/fortigate-200f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiGate 200F - Firewall Enterprise 52 Gbps | FortiStore Italia',
    meta_description: 'FortiGate 200F firewall enterprise 52 Gbps con sandboxing e ML. Per grandi organizzazioni italiane. Assistenza e supporto inclusi.',
    meta_keywords: ['fortigate 200f', 'firewall enterprise', 'firewall 52gbps', 'fortinet italia', 'firewall data center'],
    slug: 'fortigate-200f',
  },
  {
    id: '6',
    name: 'FortiGate 400E',
    model: 'FG-400E',
    category: 'FortiGate',
    subcategory: 'High-End',
    description: 'Firewall di livello carrier per service provider e grandi enterprise. Throughput fino a 66 Gbps con capacità di gestire milioni di sessioni concorrenti.',
    short_description: 'Firewall carrier-grade 66 Gbps per service provider e grandi aziende',
    price: 8999,
    features: [
      'Throughput firewall fino a 66 Gbps',
      'Carrier-grade reliability',
      'Massive concurrent sessions',
      'Advanced routing protocols',
      'Multi-tenancy support',
      '16 porte GE RJ45',
      '16 porte SFP+ 10GE',
      'Chassis ridondante',
    ],
    specifications: {
      'Throughput Firewall': '66 Gbps',
      'Throughput IPS': '11 Gbps',
      'Throughput NGFW': '5 Gbps',
      'Throughput VPN IPsec': '24 Gbps',
      'Tunnel VPN SSL': '10000',
      'Tunnel VPN IPsec': '20000',
      'Porte': '16x GE RJ45 + 16x SFP+ 10GE',
      'Storage': '2x 1.92 TB SSD',
    },
    image_url: '/images/products/fortigate-400e.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiGate 400E - Firewall Carrier Grade 66 Gbps | FortiStore Italia',
    meta_description: 'FortiGate 400E firewall carrier-grade 66 Gbps per service provider. Massima affidabilità e prestazioni. Rivenditore Fortinet Italia.',
    meta_keywords: ['fortigate 400e', 'firewall carrier grade', 'fortinet service provider', 'firewall 66gbps'],
    slug: 'fortigate-400e',
  },

  // FortiWiFi Series
  {
    id: '7',
    name: 'FortiWiFi 40F',
    model: 'FWF-40F',
    category: 'FortiWiFi',
    subcategory: 'Entry Level',
    description: 'Soluzione firewall con WiFi integrato per piccoli uffici. Combina sicurezza di rete e wireless in un unico dispositivo compatto con throughput fino a 5 Gbps.',
    short_description: 'Firewall con WiFi integrato per piccoli uffici, throughput 5 Gbps',
    price: 849,
    discount_price: 799,
    features: [
      'Firewall NGFW + WiFi integrato',
      'WiFi 6 (802.11ax)',
      'Throughput 5 Gbps',
      'Access point integrato 2x2 MU-MIMO',
      'Gestione wireless centralizzata',
      '12 porte GE RJ45',
      'Controllo accessi WiFi',
      'Guest portal',
    ],
    specifications: {
      'Throughput Firewall': '5 Gbps',
      'Throughput IPS': '600 Mbps',
      'WiFi Standard': '802.11ax (WiFi 6)',
      'WiFi Throughput': '1.2 Gbps',
      'Antenne': '2x2 MU-MIMO',
      'Utenti WiFi': '128',
      'Porte': '12x GE RJ45 + 2x GE WAN',
    },
    image_url: '/images/products/fortiwifi-40f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiWiFi 40F - Firewall con WiFi 6 Integrato | FortiStore Italia',
    meta_description: 'FortiWiFi 40F firewall con WiFi 6 integrato. Soluzione all-in-one per piccoli uffici. 5 Gbps throughput. Acquista in Italia.',
    meta_keywords: ['fortiwifi 40f', 'firewall wifi', 'wifi 6 fortinet', 'fortinet wireless', 'firewall piccolo ufficio'],
    slug: 'fortiwifi-40f',
  },
  {
    id: '8',
    name: 'FortiWiFi 60F',
    model: 'FWF-60F',
    category: 'FortiWiFi',
    subcategory: 'Entry Level',
    description: 'Firewall NGFW con WiFi 6 integrato ad alte prestazioni. Ideale per PMI che cercano una soluzione completa di sicurezza rete e wireless.',
    short_description: 'Firewall NGFW con WiFi 6, 10 Gbps throughput per PMI',
    price: 1199,
    discount_price: 1099,
    features: [
      'Firewall 10 Gbps + WiFi 6',
      '3x3 MU-MIMO WiFi',
      'SD-WAN integrato',
      'Protezione wireless avanzata',
      'Rogue AP detection',
      '16 porte GE RJ45',
      'VLAN support',
      'Captive portal',
    ],
    specifications: {
      'Throughput Firewall': '10 Gbps',
      'Throughput IPS': '1.2 Gbps',
      'WiFi Standard': '802.11ax (WiFi 6)',
      'WiFi Throughput': '1.8 Gbps',
      'Antenne': '3x3 MU-MIMO',
      'Utenti WiFi': '256',
      'Porte': '16x GE RJ45 + 2x GE WAN',
    },
    image_url: '/images/products/fortiwifi-60f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiWiFi 60F - Firewall WiFi 6 per PMI | Acquista | FortiStore Italia',
    meta_description: 'FortiWiFi 60F firewall 10 Gbps con WiFi 6 integrato. Soluzione completa per PMI italiane. SD-WAN e protezione wireless avanzata.',
    meta_keywords: ['fortiwifi 60f', 'firewall wifi pmi', 'wifi 6 enterprise', 'fortinet wireless italia'],
    slug: 'fortiwifi-60f',
  },
  {
    id: '9',
    name: 'FortiWiFi 80F',
    model: 'FWF-80F',
    category: 'FortiWiFi',
    subcategory: 'Mid-Range',
    description: 'Soluzione wireless enterprise con firewall integrato. Prestazioni elevate con WiFi 6 e throughput firewall fino a 15 Gbps per sedi aziendali di medie dimensioni.',
    short_description: 'Soluzione wireless enterprise con firewall 15 Gbps e WiFi 6',
    price: 1899,
    discount_price: 1749,
    features: [
      'Firewall 15 Gbps + WiFi 6',
      '4x4 MU-MIMO WiFi',
      'Security Fabric wireless',
      'Location-based services',
      'WiFi analytics',
      '16 porte GE RJ45',
      '2 porte SFP',
      'Roaming seamless',
    ],
    specifications: {
      'Throughput Firewall': '15 Gbps',
      'Throughput IPS': '2 Gbps',
      'WiFi Standard': '802.11ax (WiFi 6)',
      'WiFi Throughput': '2.4 Gbps',
      'Antenne': '4x4 MU-MIMO',
      'Utenti WiFi': '512',
      'Porte': '16x GE RJ45 + 2x SFP',
    },
    image_url: '/images/products/fortiwifi-80f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiWiFi 80F - Firewall Wireless Enterprise | FortiStore Italia',
    meta_description: 'FortiWiFi 80F soluzione wireless enterprise con firewall 15 Gbps. WiFi 6, Security Fabric. Per aziende italiane.',
    meta_keywords: ['fortiwifi 80f', 'wireless enterprise', 'firewall wifi 6', 'fortinet italia'],
    slug: 'fortiwifi-80f',
  },

  // FortiSwitch Series
  {
    id: '10',
    name: 'FortiSwitch 108F-POE',
    model: 'FS-108F-POE',
    category: 'FortiSwitch',
    subcategory: 'Access',
    description: 'Switch gestito Layer 2 con 8 porte PoE+ per piccoli uffici. Integrazione perfetta con FortiGate per gestione centralizzata e sicurezza estesa alla rete LAN.',
    short_description: 'Switch 8 porte PoE+ Layer 2 per piccoli uffici',
    price: 299,
    discount_price: 279,
    features: [
      '8 porte GE RJ45 PoE+',
      'Budget PoE 130W',
      'Layer 2 switching',
      'Gestione via FortiLink',
      'Security Fabric integration',
      'Fanless design',
      'Desktop/rack mount',
      'VLAN support',
    ],
    specifications: {
      'Porte PoE+': '8x GE RJ45',
      'Budget PoE': '130W',
      'Switching Capacity': '16 Gbps',
      'Layer': 'Layer 2',
      'Dimensioni': 'Compact desktop',
      'Ventole': 'Fanless',
    },
    image_url: '/images/products/fortiswitch-108f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiSwitch 108F-POE - Switch 8 Porte PoE+ | FortiStore Italia',
    meta_description: 'FortiSwitch 108F-POE switch 8 porte PoE+ gestito. Perfetto per piccoli uffici. Integrazione FortiGate. Acquista in Italia.',
    meta_keywords: ['fortiswitch 108f', 'switch poe', 'switch fortinet', 'switch 8 porte'],
    slug: 'fortiswitch-108f-poe',
  },
  {
    id: '11',
    name: 'FortiSwitch 124F-POE',
    model: 'FS-124F-POE',
    category: 'FortiSwitch',
    subcategory: 'Access',
    description: 'Switch gestito Layer 2 con 24 porte PoE+ per uffici e filiali. Budget PoE 370W per alimentare access point, telefoni VoIP e telecamere IP.',
    short_description: 'Switch 24 porte PoE+ con budget 370W per uffici',
    price: 699,
    discount_price: 649,
    features: [
      '24 porte GE RJ45 PoE+',
      'Budget PoE 370W',
      'Layer 2+ switching',
      '4 porte SFP uplink',
      'FortiLink management',
      'QoS avanzato',
      'Port security',
      'Rack mount 1U',
    ],
    specifications: {
      'Porte PoE+': '24x GE RJ45',
      'Porte Uplink': '4x SFP',
      'Budget PoE': '370W',
      'Switching Capacity': '56 Gbps',
      'Layer': 'Layer 2+',
      'Rack': '1U',
    },
    image_url: '/images/products/fortiswitch-124f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiSwitch 124F-POE - Switch 24 Porte PoE+ | FortiStore Italia',
    meta_description: 'FortiSwitch 124F-POE switch 24 porte PoE+ 370W. Layer 2+ con QoS avanzato. Ideale per uffici italiani. Rivenditore Fortinet.',
    meta_keywords: ['fortiswitch 124f', 'switch 24 porte poe', 'switch fortinet italia', 'switch gestito'],
    slug: 'fortiswitch-124f-poe',
  },
  {
    id: '12',
    name: 'FortiSwitch 148F-POE',
    model: 'FS-148F-POE',
    category: 'FortiSwitch',
    subcategory: 'Access',
    description: 'Switch enterprise Layer 2+ con 48 porte PoE+. Soluzione completa per reti aziendali con budget PoE 740W e uplink 10GE per massime prestazioni.',
    short_description: 'Switch enterprise 48 porte PoE+ con budget 740W',
    price: 1499,
    discount_price: 1399,
    features: [
      '48 porte GE RJ45 PoE+',
      'Budget PoE 740W',
      'Layer 2+ switching',
      '4 porte SFP+ 10GE',
      'Stacking support',
      'Advanced QoS',
      'IGMP snooping',
      'Rack mount 1U',
    ],
    specifications: {
      'Porte PoE+': '48x GE RJ45',
      'Porte Uplink': '4x SFP+ 10GE',
      'Budget PoE': '740W',
      'Switching Capacity': '176 Gbps',
      'Layer': 'Layer 2+',
      'Rack': '1U',
    },
    image_url: '/images/products/fortiswitch-148f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiSwitch 148F-POE - Switch 48 Porte PoE+ Enterprise | FortiStore Italia',
    meta_description: 'FortiSwitch 148F-POE switch 48 porte PoE+ 740W. Uplink 10GE, stacking. Soluzione enterprise per aziende italiane.',
    meta_keywords: ['fortiswitch 148f', 'switch 48 porte', 'switch enterprise fortinet', 'switch 10ge'],
    slug: 'fortiswitch-148f-poe',
  },
  {
    id: '13',
    name: 'FortiSwitch 224E-POE',
    model: 'FS-224E-POE',
    category: 'FortiSwitch',
    subcategory: 'Aggregation',
    description: 'Switch di aggregazione Layer 3 con 24 porte PoE+ e uplink 40GE. Ideale per core di rete aziendale con routing avanzato e alta disponibilità.',
    short_description: 'Switch Layer 3 con 24 porte PoE+ e uplink 40GE',
    price: 2999,
    discount_price: 2799,
    features: [
      '24 porte GE RJ45 PoE+',
      'Budget PoE 370W',
      'Layer 3 routing completo',
      '4 porte QSFP+ 40GE',
      'Virtual stacking',
      'OSPF, BGP support',
      'Hardware routing',
      'Ridondanza alimentazione',
    ],
    specifications: {
      'Porte PoE+': '24x GE RJ45',
      'Porte Uplink': '4x QSFP+ 40GE',
      'Budget PoE': '370W',
      'Switching Capacity': '368 Gbps',
      'Layer': 'Layer 3',
      'Rack': '1U',
    },
    image_url: '/images/products/fortiswitch-224e.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiSwitch 224E-POE - Switch Layer 3 40GE | FortiStore Italia',
    meta_description: 'FortiSwitch 224E-POE switch Layer 3 con uplink 40GE. Routing avanzato, alta disponibilità. Per data center italiani.',
    meta_keywords: ['fortiswitch 224e', 'switch layer 3', 'switch 40ge', 'fortinet core switch'],
    slug: 'fortiswitch-224e-poe',
  },

  // FortiAP Series
  {
    id: '14',
    name: 'FortiAP 231F',
    model: 'FAP-231F',
    category: 'FortiAP',
    subcategory: 'Indoor',
    description: 'Access Point WiFi 6 indoor per ambienti ufficio. Dual-radio 2x2 MU-MIMO con gestione centralizzata e integrazione Security Fabric.',
    short_description: 'Access Point WiFi 6 indoor dual-radio per uffici',
    price: 249,
    discount_price: 229,
    features: [
      'WiFi 6 (802.11ax)',
      'Dual-radio 2x2 MU-MIMO',
      'Throughput fino a 1.2 Gbps',
      'Gestione centralizzata',
      'Security Fabric integration',
      'PoE powered',
      'Montaggio soffitto/parete',
      'Guest access',
    ],
    specifications: {
      'WiFi Standard': '802.11ax (WiFi 6)',
      'Radio': 'Dual-radio 2x2',
      'Throughput': '1.2 Gbps',
      'Utenti simultanei': '128',
      'Alimentazione': 'PoE 802.3at',
      'Montaggio': 'Soffitto/parete',
    },
    image_url: '/images/products/fortiap-231f.jpg',
    in_stock: true,
    popular: true,
    new: false,
    meta_title: 'FortiAP 231F - Access Point WiFi 6 Indoor | FortiStore Italia',
    meta_description: 'FortiAP 231F access point WiFi 6 per uffici. Dual-radio, 1.2 Gbps, gestione centralizzata. Acquista in Italia.',
    meta_keywords: ['fortiap 231f', 'access point wifi 6', 'fortinet wireless', 'ap indoor'],
    slug: 'fortiap-231f',
  },
  {
    id: '15',
    name: 'FortiAP 234F',
    model: 'FAP-234F',
    category: 'FortiAP',
    subcategory: 'Indoor',
    description: 'Access Point WiFi 6 ad alte prestazioni per ambienti ad alta densità. Quad-radio 4x4 MU-MIMO ideale per uffici, aule e spazi pubblici.',
    short_description: 'Access Point WiFi 6 quad-radio per alta densità utenti',
    price: 449,
    discount_price: 399,
    features: [
      'WiFi 6 (802.11ax)',
      'Quad-radio 4x4 MU-MIMO',
      'Throughput fino a 3.5 Gbps',
      'Alta densità utenti',
      'OFDMA support',
      'Dual 5GHz radio',
      'BLE beacon integrato',
      'PoE+ powered',
    ],
    specifications: {
      'WiFi Standard': '802.11ax (WiFi 6)',
      'Radio': 'Quad-radio 4x4',
      'Throughput': '3.5 Gbps',
      'Utenti simultanei': '512',
      'Alimentazione': 'PoE+ 802.3at',
      'Porte': '2x GE RJ45',
    },
    image_url: '/images/products/fortiap-234f.jpg',
    in_stock: true,
    popular: true,
    new: true,
    meta_title: 'FortiAP 234F - Access Point WiFi 6 Alta Densità | FortiStore Italia',
    meta_description: 'FortiAP 234F access point WiFi 6 quad-radio. 3.5 Gbps, alta densità. Ideale per uffici e spazi pubblici italiani.',
    meta_keywords: ['fortiap 234f', 'wifi 6 alta densità', 'access point 4x4', 'fortinet ap italia'],
    slug: 'fortiap-234f',
  },
  {
    id: '16',
    name: 'FortiAP 431F',
    model: 'FAP-431F',
    category: 'FortiAP',
    subcategory: 'Outdoor',
    description: 'Access Point WiFi 6 outdoor weatherproof. Progettato per installazioni esterne con protezione IP67, ideale per campus, parcheggi e aree pubbliche.',
    short_description: 'Access Point WiFi 6 outdoor IP67 per esterni',
    price: 649,
    discount_price: 599,
    features: [
      'WiFi 6 outdoor',
      'Protezione IP67 weatherproof',
      'Tri-radio 4x4 MU-MIMO',
      'Throughput fino a 2.4 Gbps',
      'Range esteso',
      'Temperatura -40°C a +65°C',
      'PoE+ powered',
      'Montaggio palo/parete',
    ],
    specifications: {
      'WiFi Standard': '802.11ax (WiFi 6)',
      'Radio': 'Tri-radio 4x4',
      'Throughput': '2.4 Gbps',
      'Protezione': 'IP67',
      'Temperatura': '-40°C a +65°C',
      'Alimentazione': 'PoE+ 802.3at',
    },
    image_url: '/images/products/fortiap-431f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiAP 431F - Access Point WiFi 6 Outdoor IP67 | FortiStore Italia',
    meta_description: 'FortiAP 431F access point WiFi 6 outdoor weatherproof. IP67, -40°C a +65°C. Per installazioni esterne in Italia.',
    meta_keywords: ['fortiap 431f', 'access point outdoor', 'wifi 6 esterno', 'ap weatherproof'],
    slug: 'fortiap-431f',
  },

  // FortiAnalyzer
  {
    id: '17',
    name: 'FortiAnalyzer 200F',
    model: 'FAZ-200F',
    category: 'Management',
    subcategory: 'FortiAnalyzer',
    description: 'Appliance di logging e reporting centralizzato per piccole e medie reti. Analisi avanzata dei log con AI, compliance reporting e storage locale.',
    short_description: 'Logging e reporting centralizzato per PMI',
    price: 2499,
    discount_price: 2299,
    features: [
      'Logging centralizzato',
      'AI-powered log analysis',
      'Compliance reporting',
      'Storage locale 4TB',
      'Real-time monitoring',
      'Custom reports',
      'Supporta fino a 25 dispositivi',
      'Dashboard interattive',
    ],
    specifications: {
      'Storage': '4 TB',
      'Log Rate': '5000 logs/sec',
      'Dispositivi supportati': '25',
      'Porte': '4x GE RJ45',
      'Rack': '1U',
    },
    image_url: '/images/products/fortianalyzer-200f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiAnalyzer 200F - Logging e Reporting Fortinet | FortiStore Italia',
    meta_description: 'FortiAnalyzer 200F appliance logging centralizzato. AI analysis, compliance reporting. Per PMI italiane.',
    meta_keywords: ['fortianalyzer 200f', 'logging fortinet', 'compliance reporting', 'fortinet italia'],
    slug: 'fortianalyzer-200f',
  },

  // FortiMail
  {
    id: '18',
    name: 'FortiMail 200F',
    model: 'FML-200F',
    category: 'Email Security',
    subcategory: 'FortiMail',
    description: 'Gateway di sicurezza email per PMI. Protezione avanzata da spam, phishing, malware e ransomware con sandboxing integrato.',
    short_description: 'Gateway sicurezza email con protezione anti-phishing',
    price: 1999,
    discount_price: 1849,
    features: [
      'Anti-spam avanzato',
      'Protezione anti-phishing',
      'Sandboxing email',
      'Protezione ransomware',
      'Data loss prevention',
      'Email encryption',
      'Supporta fino a 500 mailbox',
      'Archiving opzionale',
    ],
    specifications: {
      'Mailbox supportate': '500',
      'Throughput': '1500 msg/ora',
      'Storage': '480 GB',
      'Porte': '4x GE RJ45',
      'Rack': '1U',
    },
    image_url: '/images/products/fortimail-200f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiMail 200F - Sicurezza Email Anti-Phishing | FortiStore Italia',
    meta_description: 'FortiMail 200F gateway sicurezza email. Anti-spam, anti-phishing, sandboxing. Protezione completa per PMI italiane.',
    meta_keywords: ['fortimail 200f', 'sicurezza email', 'anti-phishing', 'email security fortinet'],
    slug: 'fortimail-200f',
  },

  // FortiWeb
  {
    id: '19',
    name: 'FortiWeb 1000F',
    model: 'FWB-1000F',
    category: 'Web Security',
    subcategory: 'FortiWeb',
    description: 'Web Application Firewall per proteggere applicazioni web e API. Protezione OWASP Top 10, machine learning e protezione bot avanzata.',
    short_description: 'Web Application Firewall per protezione applicazioni web',
    price: 3999,
    discount_price: 3699,
    features: [
      'OWASP Top 10 protection',
      'Machine learning WAF',
      'API security',
      'Bot mitigation',
      'DDoS protection',
      'SSL offloading',
      'Throughput fino a 2 Gbps',
      'Virtual patching',
    ],
    specifications: {
      'Throughput': '2 Gbps',
      'HTTP Transactions': '40000/sec',
      'Server supportati': 'Illimitati',
      'Porte': '8x GE RJ45',
      'Rack': '1U',
    },
    image_url: '/images/products/fortiweb-1000f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiWeb 1000F - Web Application Firewall WAF | FortiStore Italia',
    meta_description: 'FortiWeb 1000F WAF per protezione applicazioni web. OWASP Top 10, ML, API security. Sicurezza web in Italia.',
    meta_keywords: ['fortiweb 1000f', 'waf fortinet', 'web application firewall', 'owasp protection'],
    slug: 'fortiweb-1000f',
  },

  // FortiManager
  {
    id: '20',
    name: 'FortiManager 200F',
    model: 'FMG-200F',
    category: 'Management',
    subcategory: 'FortiManager',
    description: 'Piattaforma di gestione centralizzata per dispositivi Fortinet. Configurazione, provisioning e automazione per reti multi-sede.',
    short_description: 'Gestione centralizzata per dispositivi Fortinet',
    price: 2999,
    discount_price: 2799,
    features: [
      'Gestione centralizzata',
      'Configurazione multi-device',
      'Automazione workflow',
      'Template management',
      'Change audit trail',
      'Supporta fino a 100 dispositivi',
      'Script automation',
      'SD-WAN orchestration',
    ],
    specifications: {
      'Dispositivi gestiti': '100',
      'Storage': '2 TB',
      'Porte': '4x GE RJ45',
      'Rack': '1U',
    },
    image_url: '/images/products/fortimanager-200f.jpg',
    in_stock: true,
    popular: false,
    new: false,
    meta_title: 'FortiManager 200F - Gestione Centralizzata Fortinet | FortiStore Italia',
    meta_description: 'FortiManager 200F piattaforma gestione centralizzata. Automazione, provisioning, SD-WAN orchestration. Per reti italiane.',
    meta_keywords: ['fortimanager 200f', 'gestione fortinet', 'network management', 'sd-wan orchestration'],
    slug: 'fortimanager-200f',
  },
]

// Categorie per la navigazione
export const categories = [
  {
    id: 'fortigate',
    name: 'FortiGate / FortiWiFi',
    slug: 'fortigate',
    description: 'Firewall di nuova generazione con protezione dalle minacce integrate',
    subcategories: ['Entry Level', 'Mid-Range', 'High-End'],
  },
  {
    id: 'fortiwifi',
    name: 'FortiWiFi',
    slug: 'fortiwifi',
    description: 'Firewall con WiFi integrato per sicurezza rete e wireless',
    subcategories: ['Entry Level', 'Mid-Range'],
  },
  {
    id: 'fortiswitch',
    name: 'FortiSwitch',
    slug: 'fortiswitch',
    description: 'Switch gestiti con integrazione Security Fabric',
    subcategories: ['Access', 'Aggregation'],
  },
  {
    id: 'fortiap',
    name: 'FortiAP',
    slug: 'fortiap',
    description: 'Access Point WiFi 6 per reti wireless sicure',
    subcategories: ['Indoor', 'Outdoor'],
  },
  {
    id: 'management',
    name: 'Management & Analytics',
    slug: 'management',
    description: 'Soluzioni di gestione, logging e analisi',
    subcategories: ['FortiAnalyzer', 'FortiManager'],
  },
  {
    id: 'security',
    name: 'Email & Web Security',
    slug: 'security',
    description: 'Protezione email e applicazioni web',
    subcategories: ['FortiMail', 'FortiWeb'],
  },
]
