// Keywords SEO ottimizzate per il mercato italiano
export const italianKeywords = {
  primary: [
    'fortinet italia',
    'fortinet roma',
    'fortinet milano',
    'comprare fortinet italia',
    'rivenditore fortinet italia',
    'firewall fortinet italia',
    'fortigate italia',
    'sicurezza informatica italia',
  ],
  secondary: [
    'fortinet torino',
    'fortinet napoli',
    'fortinet firenze',
    'fortinet bologna',
    'fortinet venezia',
    'fortinet genova',
    'fortinet palermo',
    'fortinet bari',
    'firewall aziendale',
    'protezione rete aziendale',
    'cybersecurity italia',
    'fortinet prezzo',
    'fortigate prezzo',
    'firewall ngfw',
    'fortigate 40f',
    'fortigate 60f',
    'fortigate 80f',
    'fortigate 100f',
    'fortiwifi italia',
    'fortiswitch italia',
    'fortiap italia',
    'fortianalyzer italia',
    'fortmail italia',
    'fortiweb italia',
    'fortimanager italia',
    'forticare supporto',
    'licenze fortinet',
    'assistenza fortinet italia',
  ],
  longTail: [
    'migliori firewall fortinet per pmi',
    'firewall fortinet per piccole imprese',
    'come scegliere firewall fortinet',
    'confronto modelli fortigate',
    'fortinet vs altri firewall',
    'installazione firewall fortinet',
    'configurazione fortigate',
    'protezione ransomware fortinet',
    'vpn aziendale fortinet',
    'fortinet sd-wan italia',
    'fortinet zero trust',
    'firewall fortinet prezzi competitivi',
    'offerte fortinet italia',
    'promozioni firewall fortinet',
  ],
  regional: {
    nord: ['fortinet lombardia', 'fortinet piemonte', 'fortinet veneto', 'fortinet emilia romagna'],
    centro: ['fortinet lazio', 'fortinet toscana', 'fortinet marche', 'fortinet umbria'],
    sud: ['fortinet campania', 'fortinet puglia', 'fortinet sicilia', 'fortinet calabria'],
  },
}

export const productKeywords = {
  fortigate: [
    'fortigate firewall',
    'next generation firewall',
    'utm firewall',
    'firewall hardware',
    'fortigate ngfw',
    'firewall ips ids',
    'firewall application control',
    'firewall web filtering',
  ],
  fortiwifi: [
    'fortiwifi wireless',
    'firewall wifi integrato',
    'access point firewall',
    'soluzione wifi sicura',
  ],
  fortiswitch: [
    'switch gestiti fortinet',
    'fortiswitch poe',
    'switch layer 2 layer 3',
    'switch sicuri',
  ],
  fortiap: [
    'access point fortinet',
    'wifi aziendale',
    'access point gestiti',
    'wifi controller',
  ],
}
